[package]
name = "ext"
version = "0.1.0"
edition = "2018"
authors = ["Ian Ker-Seymer <hello@ianks.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { git = "https://github.com/matsadler/magnus" }
wasmtime = "0.40.0"
