---
name: CI

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        ruby: ["2.7", "3.0", "3.1", "head"]
    steps:
      - uses: actions/checkout@v3

      - name: Remove Gemfile.lock
        run: rm Gemfile.lock

      - uses: oxidize-rb/actions/setup-ruby-and-rust@main
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cargo-cache: true
          cache-version: v1

      - name: Compile rust ext
        run: bundle exec rake compile

      - name: Run ruby tests
        run: bundle exec rake spec

      - name: Run ruby tests (hard-mode with GC.stress)
        run: bundle exec rake spec
        env:
          GC_STRESS: "true"

      - name: Lint ruby
        run: bundle exec rake standard

      - name: Lint rust
        run: cargo clippy && cargo fmt --check

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Remove Gemfile.lock
        run: rm Gemfile.lock

      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.1"
          rustup-toolchain: "nightly"
          bundler-cache: true
          cargo-cache: true
          cache-version: v1

      - name: Compile rust ext
        run: bundle exec rake compile

      - name: Generate doc
        run: bundle exec rake doc
